### ISSUE TITLE
multi-user support

### ISSUE THREAD

**Issue by dmerejkowsky** [dmerejkowsky/static_tl#2]
Something like

```toml
site_url = "http://example.com"

[auth]
api_key = "XXX"
api_secret = "YYY"

[[users]]

[users.dmerej]
with_replies = false

[users.other_account]
```
